controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints: ["Kepala Putar", "Leher Putar", "Paha Atas Kanan", 
      "Paha Atas Kiri", "Paha Bawah Kanan", "Paha Bawah Kiri",
      "Paha Kanan Putar", "Paha Kiri Putar", "Lutut Kanan",
      "Lutut Kiri", "Kaki Kanan Atas", "Kaki Kiri Atas", "Kaki Kanan Bawah", "Kaki Kiri Bawah", 
      "Lengan Kiri", "Bahu Tangan Kiri", "Tangan Kiri", "Lengan Kanan", "Bahu Tangan Kanan", "Tangan Kanan"]
    # joints: ["Kepala Putar", "Leher Putar"]
    command_interfaces: ["position"]
    state_interfaces: ["position"]